# Generated by Django 3.2.8 on 2021-12-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviexpress', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserve',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.CharField(default='', max_length=30),
        ),
    ]
