# Generated by Django 3.2.8 on 2021-12-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviexpress', '0003_auto_20211201_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
