# Generated by Django 3.2.8 on 2021-12-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviexpress', '0004_auto_20211201_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
